import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(import.meta.dir, '..');
const OUTPUT = path.join(ROOT, 'CODEMAP.md');

const SKIP_DIRS = new Set([
  'node_modules', 'dist', 'build', '.git', '.svelte-kit', '.agents'
]);
const INDEX_EXT = new Set(['.ts', '.svelte', '.js']);
const ENTRY_FILES = new Set(['server.ts', 'svelte.config.js', 'routes/api.ts']);

function walk(dir: string, results: string[] = []): string[] {
  let entries: fs.Dirent[] = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }

  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(full, results);
    } else if (entry.isFile()) {
      const ext = path.extname(entry.name);
      if (INDEX_EXT.has(ext)) results.push(full);
    }
  }
  return results;
}

function extractExports(content: string, ext: string) {
  const exports: any[] = [];
  const seen = new Set<string>();

  if (ext === '.svelte') {
    const scriptMatch = content.match(/<script[^>]*>([\s\S]*?)<\/script>/);
    if (!scriptMatch) return exports;
    content = scriptMatch[1];
  }

  const patterns = [
    [/export\s+const\s+(\w+)/g, 'const'],
    [/export\s+function\s+(\w+)/g, 'function'],
    [/export\s+async\s+function\s+(\w+)/g, 'function'],
    [/export\s+interface\s+(\w+)/g, 'interface'],
    [/export\s+type\s+(\w+)/g, 'type'],
    [/export\s+class\s+(\w+)/g, 'class'],
    [/export\s+default\s+(?:function|class)?\s*(\w+)?/g, 'default'],
  ] as const;

  for (const [regex, kind] of patterns) {
    let match: RegExpExecArray | null;
    regex.lastIndex = 0;
    while ((match = regex.exec(content)) !== null) {
      const name = match[1] || 'default';
      const key = `${kind}:${name}`;
      if (!seen.has(key)) {
        seen.add(key);
        exports.push({ name, kind });
      }
    }
  }
  return exports;
}

function main() {
  const files = walk(ROOT).sort();
  const entries = [];

  for (const absPath of files) {
    const rel = path.relative(ROOT, absPath).replace(/\\/g, '/');
    const ext = path.extname(absPath);
    const content = fs.readFileSync(absPath, 'utf-8');
    
    entries.push({
      path: rel,
      lines: content.split('\n').length,
      exports: extractExports(content, ext),
      isEntry: ENTRY_FILES.has(rel),
    });
  }

  const totalLines = entries.reduce((s, e) => s + e.lines, 0);
  
  let md = `# CODEMAP.md\n\n> Auto-generated by \`bun run scripts/codemap.ts\`.\n\n`;
  md += `## Stats\n- Files indexed: ${entries.length}\n- Total lines: ${totalLines}\n\n`;
  
  md += `## File Tree\n\n`;
  for (const e of entries) {
    const star = e.isEntry ? ' ★' : '';
    const exp = e.exports.length > 0 ? ` — ${e.exports.map(x => x.name).slice(0,5).join(', ')}` : '';
    md += `- \`${e.path}\`${star} (${e.lines}L)${exp}\n`;
  }
  
  fs.writeFileSync(OUTPUT, md);
  console.log(`CODEMAP.md generated: ${OUTPUT}`);
}

main();
