name: CI & CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Svelte Check & Typecheck
        run: bun run check

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            # TODO: Ganti path di bawah dengan lokasi project aslimu di server
            cd ~/narko
            
            git pull origin master
            bun install
            bun run db:migrate
            bun run build
            
            # TODO: Sesuaikan dengan command untuk merestart server kamu (misal PM2)
            bunx --bun pm2 reload narko-app
